baseURL = 'https://je1zzz.github.io/github-page-obsidian/'
locale = 'zh-CN'
defaultContentLanguage = 'zh'
title = '🍎zhm notebook🍎'
theme = 'hugo-bearblog'
enableRobotsTXT = true
timeZone = 'Asia/Shanghai'

[params]
  description = 'Rebuild my broken brain。'
  dateFormat = '2006-01-02'
  enablePostNavigator = true

[taxonomies]
  tag = 'tags'

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menus.main]]
  name = 'Article'
  pageRef = '/blog'
  weight = 20
[[menus.main]]
  name = 'Group'
  pageRef = '/tags'
  weight = 30

[markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
  style = 'friendly'
  lineNos = false
